POST http://192.168.1.248:3000/api/waypoints
Content-Type: application/json
Authorization: Bearer linuskang@bubblyceo

{
    "name": "Riverside Bubbler",
    "latitude": -27.702,
    "longitude": 153.005,
    "description": "Next to the riverside walking track",
    "amenities": ["water", "shelter", "bench"],
    "image": "https://example.com/riverside-bubbler.jpg",
    "maintainer": "City Council",
    "addedByUserId": "cmg4ut2os0000zfx0646smbkr"
}
